### ISSUE TITLE
cargo build is invoked at CMake configure step

### ISSUE THREAD

**Issue by Be-ing** [KDAB/cxx-qt#106]
I found this rather surprising. I expected cargo to be invoked in the CMake build step, not the configure step.

**Comment by ahayzen-kdab** [comment]
@Be-ing  So the CXX macros (and our own CXX-Qt macros) generate C++ source files alongside the Rust library binary that is generated. We currently need the list of generated C++ sources so that we can then build the combined binary of C++ sources + Rust static library and then link it to Qt, which currently means we need the build script of Rust to run at the configure stage to give us these values early enough.

Some colleagues with CMake knowledge have been looking at this internally to see if we can improve the flow, but we need to have some more time allocated to improve this :-)

For now I would ignore how the CMake works as we know it's something we want to try and improve / change in the future.

**Comment by Be-ing** [comment]
Yeah, this seems like a tricky situation to detangle. I'm not sure it is possible to move the Rust build into the CMake build step.

**Comment by Be-ing** [comment]
Perhaps it could help to publish a CLI bin crate, which could be packaged separately, to generate the C++ instead of relying on the Rust's build.rs to invoke CxxQtBuilder? This would be similar to cxx's [cxxbridge](https://github.com/dtolnay/cxx#non-cargo-setup) tool.

**Comment by ahayzen-kdab** [comment]
That's an interesting idea :-) Then the options that are provided by CxxQtBuilder would instead be in the CMake wrapper around the equivalent of cxxbridge tool. Could be an option going forward, I'll discuss this with the folks looking at the CMake side when I have a chance :-)

**Comment by Be-ing** [comment]
I think a CLI tool could help with packaging too. Distributions could package the CLI tool together with the CxxQt.cmake module so applications wouldn't need to vendor the CxxQt.cmake module in their repository.

**Comment by ahayzen-kdab** [comment]
Discussion for this is now available here https://github.com/KDAB/cxx-qt/discussions/146
