### ISSUE TITLE
issue building with qt6.8

### ISSUE THREAD

**Issue by CelestialCrafter** [KDAB/cxx-qt#1117]
hi! im trying to build my project with qt6.8.0, but im getting  this error:

`Cannot mix incompatible Qt library (6.7.2) with this library (6.8.0)`

i dont know if this is an issue with cxx-qt itsself, or something else on my system.

`qmake -v`:
```
QMake version 3.1
Using Qt version 6.8.0 in /nix/store/az405iari637x43iwnxk2wf10ajyalb6-qt-full-6.8.0/lib
```

relevant Cargo.toml:

```
[dependencies]
cxx = "1.0.129"
cxx-qt = "0.7.0"
cxx-qt-lib = { version = "0.7.0", features = ["qt_full"] }

[build-dependencies]
cxx-qt-build = { version = "0.7", features = [ "link_qt_object_files" ] }
```

please let me know if im doing something wrong, or if i need to downgrade till 6.7.2 till cxx-qt upgrades. thank you!

**Comment by ahayzen-kdab** [comment]
Hey,

This sounds like one of the Qt libraries / modules has been previously built for 6.7.2 or you are still somehow having a Qt 6.7 library in your environment.

Have you tried a clean rebuild of the project ? (eg delete the target/ and/or build/ folder?)

Otherwise if that doesn't work what does `ldd` show on the binary executable which libraries it is wanting to use?

**Comment by CelestialCrafter** [comment]
i found [this](https://github.com/NixOS/nixpkgs/issues/349618) issue which leads me to believe i somehow have 2 conflicting qt's on my system (as you said). i'm going to try updating my system now
