### ISSUE TITLE
Auto-imported Pin breaks IDE integration

### ISSUE THREAD

**Issue by ishitatsuyuki** [KDAB/cxx-qt#417]
It looks like https://github.com/KDAB/cxx-qt/commit/5797eb75fcd88e453cff976e2dc74b66e1d556e7 added Pin as an implicit import. However, this means that code that manually imports `std::pin::Pin` will fail:

```
error[E0252]: the name `Pin` is defined multiple times
 --> src/bridge.rs:4:9
  |
1 | #[cxx_qt::bridge]
  | ----------------- previous import of the type `Pin` here
...
4 |     use std::pin::Pin;
  |         ^^^^^^^^^^^^^ `Pin` reimported here
  |
  = note: `Pin` must be defined only once in the type namespace of this module
```

Meanwhile, if I *don't* import Pin, then IntelliJ Rust wouldn't be able to resolve it:

![image](https://user-images.githubusercontent.com/12389383/213637697-c6ed1300-4c27-496a-b3d4-f368f6f521b0.png)

This is a nuisance because it keeps red lines in my code when it's not relevant, and it also breaks code completion to some extent.

Perhaps, it would be better to keep generated imports under an alias that doesn't collide (e.g. `use std::pin::Pin as _Pin`)?

**Comment by ahayzen-kdab** [comment]
So currently we have a `use std::pin::Pin` in the scope of the invokables. The original reason for this is that in a `#[cxx::bridge]` you write `Pin<T>`, so for invokables if the developer is able to just write `Pin<T>` then we can pass that through to the inner CXX bridge without having to parse and modify the signature. We then have that `use std::pin::Pin` in the scope of the invokables so that they continue working there without modification.

Maybe we do need to start parsing the signature of methods and rewrite `Pin<T>` to `std::pin::Pin<T>` so that the `use std::pin::Pin` can be removed, unless there is another way around this :thinking: 

However I note that Visual Studio Code does not suffer from this issue and is able to determine that it is a `Pin` type with the correct code completion, is IntelliJ Rust using `rust-analyzer` like vscode ?

Note that we also do the same with `UniquePtr<T>` (eg `type UniquePtr<T> = cxx::UniquePtr<T>;`) so whatever solution is considered here should be considered for that too (and `SharedPtr` or any other types CXX has in it's bridges exposed).

**Comment by ahayzen-kdab** [comment]
New API should help with this as `impl` blocks end up outside the bridge.
