### ISSUE TITLE
QModelIndex::internalId() needed for trees

### ISSUE THREAD

**Issue by kermitfrog** [KDAB/cxx-qt#719]
Possible tasks:

- [ ] Add Qt types to cxx-qt-lib, eg `quintptr` so it can be used easily in bridges https://doc.qt.io/qt-6/qttypes.html
- [ ] Add an alias in a C++ header somewhere for `c_void` as suggested in https://github.com/dtolnay/cxx/issues/1049
- [x] Add support for methods in existing types which return these types and were missed before, eg `QModelIndex::internalId`

Original description:

I am trying to create a tree-model to provide data to QML. 
The normal way is to use QAbstractItemModel, but there is a problem:
The view might request an items parent by calling QModelIndex::parent().

In a list or table, where items never have parents, this would simply return an invalid QModelIndex().
The current item can then be found simply by it's row and column.

In a tree, the parent is needed as well, for which I need to know the current Item, for which I need the parent ...
That problem is usually solved by storing a pointer or id in the QModelIndex, which is set by QAbstractItemModel::createIndex() and retrieved by QModelIndex::internalId() (or internalPointer()) -- but cxx_qt does not provide access to these methods.

I thought about a workaround by following the parents up to the root level, remembering all the rows and then down again to find the right item, but as the documentation of QAbstractItemModel::parent states:

> When reimplementing this function in a subclass, be careful to avoid calling QModelIndex member functions, such as QModelIndex::parent(), since indexes belonging to your model will simply call your implementation, leading to infinite recursion.

so that would not work.

The only other way I can think of, that might possibly work, is subclassing QModelIndex, which I'd like to avoid.

**Comment by ahayzen-kdab** [comment]
Thanks for taking the time to report this issue :-)

We haven't wrapped those methods in CXX-Qt yet, we could add support for the internalPointer quite easily by the looks of things or if added support for `quintptr` that would also be simple to add.

Currently you could extend the `QModelIndex` type with your own type, for example

You could define your own type to extend the `cxx_qt_lib` one.

```rust
#[repr(transparent)]
pub struct QModelIndexExtended(cxx_qt_lib::QModelIndex);

unsafe impl cxx::ExternType for QModelIndexExtended {
    type Id = cxx::type_id!("QModelIndex");
    type Kind = cxx::kind::Trivial;
}
```

Then in your bridge define the type with additional methods

```rust
    unsafe extern "C++" {
        include!("cxx-qt-lib/qmodelindex.h");
        type QModelIndex = super::QModelIndexExtended;

        type c_void;

        // TODO: could build quintptr as a type then this would work too
        // or create a trampoline from C++ which casts to a type CXX understands
        // #[rust_name = "internal_id"]
        // fn internalId(self: &QModelIndex) -> quintptr;

        #[rust_name = "internal_pointer"]
        unsafe fn internalPointer(self: &QModelIndex) -> *mut c_void;
    }
```

Then in a header that is included you would also need `using c_void = void;` (eg i put it in the `qmodelindex.h` but you could add another header and then include it).

These are all normal CXX types so follow the normal CXX rules.

But I also think that we should consider adding built in support for the `c_void` cast in C++ for CXX ( https://github.com/dtolnay/cxx/issues/1049 ) and we should consider adding types to cxx-qt-lib for things like quintptr so that these can be easily expressed. Then we could add some of these extra methods to the built-in types.

**Comment by kermitfrog** [comment]
Thanks for providing code, but unfortunetely I can not get it to compile.
I tried several things and re-read the docs (I'm new to cxx and really wanted to understand why it's not working - as far as I understand it should..), but I always end up with this error:

> error: ‘c_void’ in namespace ‘::’ does not name a type; did you mean ‘void’?
warning:   286 | using c_void = ::c_void;
warning:       |                  ^~~~~~
warning:       |                  void

Do you have any ideas?
Otherwise I'll just wait until #724 is merged.

**Comment by ahayzen-kdab** [comment]
In a C++ header you need to put `using c_void = void;` and then include it. Something like the following might work (untested) ...

`cpp/my_header.h`
```cpp
using c_void = void;
```

Then in the bridge you need to include it
```rust
#[cxx_qt::bridge]
mod ffi {
...
    unsafe extern "C++ {
        include!("my_header.h");
    }
...
}
```

Then you need to make sure that the header is in the C++ include path, so in the `build.rs` ensure that you have something that includes the `cpp` folder.
```rust
fn main() {
    CxxQtBuilder::new()
        ...
        .cc_builder(|cc| {
            // needs to point to the folder where the header is
            cc.include("cpp");
        })
        ...
        .build();
}
```
